name: "Synopsys Intelligent Security Scan"

on:
  push:
    branches: [ main ]
  # pull_request:
    # branches: [ main ]

jobs:
  analyze:
    name: Analyze
    runs-on: self-hosted
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        # We must fetch at least the immediate parents so that if this is
        # a pull request then we can checkout the head.
        fetch-depth: 2

    # If this run was triggered by a pull request event, then checkout
    # the head of the pull request instead of the merge commit.
    - run: git checkout HEAD^2
      if: ${{ github.event_name == 'pull_request' }}
      
    - name: IO Client Run End to End
      run: |
            if [ ! -d 'io_client-${{secrets.IO_CLIENT_VERSION}}-${{secrets.RUNNER_OS_TYPE}}' ]; then
              wget "${{secrets.IO_CLIENT_URL}}/download/io_client-${{secrets.IO_CLIENT_VERSION}}-${{secrets.RUNNER_OS_TYPE}}.zip"
              unzip -o io_client-${{secrets.IO_CLIENT_VERSION}}-${{secrets.RUNNER_OS_TYPE}}.zip
            fi
            chmod +x io_client-${{secrets.IO_CLIENT_VERSION}}-${{secrets.RUNNER_OS_TYPE}}/io  
            io_client-${{secrets.IO_CLIENT_VERSION}}-${{secrets.RUNNER_OS_TYPE}}/io --stage io --stage execution --stage workflow
      env:
        SYNOPSYS_IO_Workflow_Engine_Version : 2022.4.1
        SYNOPSYS_IO_io_server_token: ${{secrets.IO_SERVER_TOKEN}}
        SYNOPSYS_IO_project_name: "io-poc/poc-90"
        SYNOPSYS_IO_io_server_url: ${{secrets.IO_SERVER_URL}}
        SYNOPSYS_IO_persona_type: devsecops
        SYNOPSYS_IO_polaris_instanceurl: ${{secrets.POLARIS_SERVER_URL}}
        SYNOPSYS_IO_polaris_authtoken:  ${{secrets.POLARIS_ACCESS_TOKEN}}
        SYNOPSYS_IO_polaris_projectName: "insecure-bank"
        SYNOPSYS_IO_sigma_downloadurl: ${{secrets.SIGMA_DOWNLOAD_URL}}
        SYNOPSYS_IO_Jira_HostUrl: <jira_host_url>
        SYNOPSYS_IO_Jira_Username: <jira_user_name>
        SYNOPSYS_IO_Jira_AuthToken: ${{secrets.JIRA_AUTH_TOKEN}}
        SYNOPSYS_IO_Jira_IssueType: <jira_issue_type>
        SYNOPSYS_IO_Jira_Project_Key: <jira_project_key>
        SYNOPSYS_IO_Jira_Assignee: <jira_assignee>
        SYNOPSYS_IO_slack_channelIdentifier: "C03ENPM4C90"
        SYNOPSYS_IO_slack_bearerToken: ${{secrets.SLACK_TOKEN}}
        SYNOPSYS_IO_jira_issuesquery: <jira_issues_query>
        SYNOPSYS_IO_jira_project_name: <jira_projet_name>
        SYNOPSYS_IO_scm_type: <scm_type>
        SYNOPSYS_IO_scm_owner: <scm_owner>
        SYNOPSYS_IO_scm_repository_name: <scm_repository_name>
        SYNOPSYS_IO_scm_repository_branch_name: <scm_respository_branch_name>
        SYNOPSYS_IO_github_token: ${{secrets.GTH_AUTH_TOKEN}}
        SYNOPSYS_IO_github_username: <github_username>
        SYNOPSYS_IO_github_apiUrl: <github_api_url>
        SYNOPSYS_IO_project_release_type: "major"
        SYNOPSYS_IO_Blackduck_AuthToken: ${{secrets.BLACKDUCK_TOKEN}}
        SYNOPSYS_IO_Blackduck_ProjectName: "insecure-bank"
        SYNOPSYS_IO_Blackduck_InstanceUrl: ${{secrets.BLACKDUCK_URL}}
        SYNOPSYS_IO_Blackduck_ProjectVersion: 1.0
